#!/usr/bin/env python3
#print("Hello, world")
import tkinter as tk
import subprocess

def show_values(value):
	print (value)
	temp="-set "+value
	print (temp)
	subprocess.call(["xbacklight","-set",value])  # doesn't capture output
	#subprocess.call(["ls","-l"])  # doesn't capture output

class Display:

	def __init__(self):

		self.root=tk.Tk()
		self.root.title("xbacklight")

		self.slide1=tk.Scale(self.root, from_=0, to=100, orient=tk.HORIZONTAL, command=show_values)
		print (self.slide1.get())		
		self.slide1.pack()
		self.root.mainloop()

dis =Display()
